spring:
  banner:
    location: classpath:folderexample/banner.txt
#=================================================== Datasource
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false
    username: root
    password: 44210977-D
#=================================================== Datasource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #check if entities are sync with the DB, if not, the DB is updated
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5Dialect
        